In [3]:
import pandas as pd
df = pd.read_csv("raw_data.csv")

## groupby()
### a powerful tool used to split data into groups based on specific criteria, apply operations to those groups, and then combine the results

In [4]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [8]:

# hr country ki alg group hoga[group] + hr group k income ka mean[aggregation]
df.groupby("country")['income'].mean()   # mean income of each group 
df.groupby("country")['income'].min()    # min income of each group 
df.groupby("country")['income'].max()    # max income of each group

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       62000.0
Name: income, dtype: float64

In [10]:
# konsa aisa parameter hai jiske basis pr hum group bana rahe hai = groupby() {here parameter => 'gender'}

df.groupby("gender")['income'].mean()

gender
Female     65666.666667
Male       54800.000000
Unknown    47000.000000
Name: income, dtype: float64

## agg()
### used to apply one or more operations (aggregations) across a specified axis of a DataFrame or Series

In [11]:
# groups pr multiple function apply krne k liye hota hia agg()

#Example-1

df.groupby("gender")['income'].agg(['mean', 'min', 'max'])

                 mean      min      max
gender
Female   65666.666667  62000.0  73000.0
Male     54800.000000  45000.0  68000.0
Unknown  47000.000000  47000.0  47000.0

In [12]:
# Exapmle-2

df.groupby("country")['income'].agg(['mean', 'min', 'max']) 

# aggregate(): an alias (an alternative name for an existing object, module, or type) for agg()

df.groupby("country")['income'].aggregate(['mean', 'min', 'max'])

            mean      min      max
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  47000.0  62000.0

## Renaming + groupby() + agg()

In [15]:
# TO CHANGE HEAD / LABELS TO RENAME THESE COLUMNS  [mean , min , max]

df.groupby("country")['income'].aggregate(avg_salary = 'mean', min_salary = 'min', max_salary = 'max')

         avg_salary  min_salary  max_salary
country
Canada      62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0
India       73000.0     73000.0     73000.0
Mexico      45000.0     45000.0     45000.0
Spain           NaN         NaN         NaN
USA         55400.0     47000.0     62000.0

In [23]:
# alg-alg columns pr alg-alg aggregate functions ko apply kr skte hai

# Example-1
df.groupby("country").agg({
   "income" : "mean",
    "age" : "mean"    
}) 



# Example-2
df.groupby("country").agg({
   "income" : "max",
    "age" : "mean"    
})

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      62000.0  29.5

In [22]:
# renaming columns

# Example-3
df.groupby("country").agg(    # to add labels/ rename columns
   max_salary = ("income" , "max"),
   avg_age = ("age" , "mean" )  
)

         max_salary  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.5