In [1]:
import pandas as pd

1. pd.melt(): 

Wide to LongUse melt when you want to "unpivot" your data. It’s perfect when you have several columns that represent the same type of 
measurement (e.g., "Jan Sales", "Feb Sales") and you want them in one single column.
    
Syntax: df.melt(id_vars=['col1'], value_vars=['col2', 'col3'], var_name='new_var', value_name='new_val')
    
Key Parameters:
    id_vars: Columns you want to keep as they are (identifiers).
    value_vars: Columns you want to unpivot / "melt" into rows.
    var_name: Name for the new column containing the old headers.
    value_name: Name for the new column containing the actual data values.
    
Example:Converting a table of students and their marks in different subjects into a list where each row is one subject's mark for one student.


| Feature     | `melt`                                 | `pivot`                                    |
| ----------- | -------------------------------------- | ------------------------------------------ |
| Goal        | Wide → Long                            | Long → Wide                                |
| Typical Use | Preparing data for analysis / plotting | Creating summary tables / reports          |
| Outcome     | More rows, fewer columns               | Fewer rows, more columns                   |
| Aggregation | No                                     | No (`pivot_table` is used for aggregation) |

In [6]:

df = pd.DataFrame({
     "country" : ['USA', 'USA', 'India','India'],
    "year" : [2020, 2021, 2020, 2021],
    'sales' : [100, 120, 90, 110],
    'profit': [20, 25, 18, 22],
    'tax' : [10, 20, 30, 40]
})

In [7]:
df

  country  year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   40

In [17]:
melted_df = df.melt(
    id_vars=["country", 'year'],  # want as it is
    value_vars=['sales', 'profit', 'tax'],  # to melt
    var_name='metrics',  # name for new column
    value_name='value'    # name for the new column having actual data values
)

melted_df

   country  year metrics  value
0      USA  2020   sales    100
1      USA  2021   sales    120
2    India  2020   sales     90
3    India  2021   sales    110
4      USA  2020  profit     20
5      USA  2021  profit     25
6    India  2020  profit     18
7    India  2021  profit     22
8      USA  2020     tax     10
9      USA  2021     tax     20
10   India  2020     tax     30
11   India  2021     tax     40

2. df.pivot(): 

Long to WideUse pivot to reshape your data into a more readable "report" style or to prepare it for certain machine learning models.
It takes values from one column and turns them into multiple column headers.

Syntax: df.pivot(index='col1', columns='col2', values='col3')
    
Key Parameters:
    index: Column/ label to use for the new rows. {The label should be different for each specific row}
    columns: Column whose unique values will become the new column headers.
    values: Column(s) used to fill the cells of the new table.

In [15]:
original = melted_df.pivot(
    index= ['country', 'year'],   # we use a pair or a name which is unique for every single element to separate it in single rows
    columns = 'metrics',          # apne andr hr type k head/label ka separate naya column banayga  
    values = 'value'              # inn values se upr k columns ko fill krna chahte hai
)

In [16]:
original

metrics       profit  sales  tax
country year
India   2020      18     90   30
        2021      22    110   40
USA     2020      20    100   10
        2021      25    120   20