In [1]:
import pandas as pd

In [3]:
df_customers = pd.DataFrame({
    'customer_id' : [1, 2, 3, 4],
    'name' : ['Adam', 'Biman', 'Charlie', 'Dora']
})

df_orders = pd.DataFrame({
    "order_id" : [101, 102, 103, 104],
    'customer_id' : [2, 1, 4, 5],
    'amount' : [250, 280, 120, 300]
})

In [4]:
df_customers

   customer_id     name
0            1     Adam
1            2    Biman
2            3  Charlie
3            4     Dora

In [5]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     280
2       103            4     120
3       104            5     300

In [10]:
# inner join  ==> yeh sirf matching(common) values leta hai
   
pd.merge(df_customers,df_orders, on = 'customer_id')        # the parameter which has to be taken to print the commons = 'on'
                                                            # on the basis of 'customer_id' 
                                                           # vo print honge jo dono main common ho

   customer_id   name  order_id  amount
0            1   Adam       102     280
1            2  Biman       101     250
2            4   Dora       103     120

In [11]:
# left join 

pd.merge(df_customers,df_orders, on = 'customer_id', how = 'left')        # the parameter which has to be taken to print the commons = 'on'
                                                            # left k saare print honge + jo right main missing hai usse 'Nan' se fill kr denge

   customer_id     name  order_id  amount
0            1     Adam     102.0   280.0
1            2    Biman     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dora     103.0   120.0

In [12]:
# right join 

pd.merge(df_customers,df_orders, on = 'customer_id', how = 'right')        # 'how' ==> konsi side ka join krna hai
                                                                     # right k saare print honge + jo left main missing hai usse 'Nan' se fill kr denge

   customer_id   name  order_id  amount
0            2  Biman       101     250
1            1   Adam       102     280
2            4   Dora       103     120
3            5    NaN       104     300

In [13]:
# Outer join 

pd.merge(df_customers,df_orders, on = 'customer_id', how = 'outer')    
                                                                     # dono k saare print honge + jo missing hai usse 'Nan' se fill kr denge

   customer_id     name  order_id  amount
0            1     Adam     102.0   280.0
1            2    Biman     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dora     103.0   120.0
4            5      NaN     104.0   300.0