In [44]:
# import os

# print(os.getcwd())
# print(os.listdir())

In [2]:
import pandas as pd

df = pd.read_csv("../_03_Import_Data/employee_data.csv")
print(df)


# using the csv from another folder to work on

  Employee ID           Name  Age     Department  Salary
0      EMP101   Aarav Sharma   25             HR   35000
1      EMP102    Priya Verma   29        Finance   52000
2      EMP103    Rohan Mehta   31             IT   68000
3      EMP104   Sneha Kapoor   27      Marketing   47000
4      EMP105   Vikram Singh   35     Operations   75000
5      EMP106     Neha Joshi   24          Sales   40000
6      EMP107     Aditya Rao   30             IT   72000
7      EMP108     Kavya Nair   28             HR   39000
8      EMP109   Manish Gupta   33        Finance   81000
9      EMP110  Isha Malhotra   26  Customer Care   36000

In [46]:
df

  Employee ID           Name  Age     Department  Salary
0      EMP101   Aarav Sharma   25             HR   35000
1      EMP102    Priya Verma   29        Finance   52000
2      EMP103    Rohan Mehta   31             IT   68000
3      EMP104   Sneha Kapoor   27      Marketing   47000
4      EMP105   Vikram Singh   35     Operations   75000
5      EMP106     Neha Joshi   24          Sales   40000
6      EMP107     Aditya Rao   30             IT   72000
7      EMP108     Kavya Nair   28             HR   39000
8      EMP109   Manish Gupta   33        Finance   81000
9      EMP110  Isha Malhotra   26  Customer Care   36000

## df.head

In [47]:
# By default : starting ki 5 rows k data ko print krvata hai

df.head()

  Employee ID          Name  Age  Department  Salary
0      EMP101  Aarav Sharma   25          HR   35000
1      EMP102   Priya Verma   29     Finance   52000
2      EMP103   Rohan Mehta   31          IT   68000
3      EMP104  Sneha Kapoor   27   Marketing   47000
4      EMP105  Vikram Singh   35  Operations   75000

## df.tail

In [48]:
# By default : last ki 5 (trailing 5) rows k data ko print krvata hai

df.tail()

# but to print only 2 rows 
df.tail(2)

  Employee ID           Name  Age     Department  Salary
8      EMP109   Manish Gupta   33        Finance   81000
9      EMP110  Isha Malhotra   26  Customer Care   36000

## df.sample

In [49]:
# to print any random row 

df.sample()

# to print any given number of random value, let's say - 5
df.sample(5)

  Employee ID           Name  Age     Department  Salary
9      EMP110  Isha Malhotra   26  Customer Care   36000
5      EMP106     Neha Joshi   24          Sales   40000
1      EMP102    Priya Verma   29        Finance   52000
6      EMP107     Aditya Rao   30             IT   72000
4      EMP105   Vikram Singh   35     Operations   75000

## df.info

In [50]:
# Random summary of our data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee ID  10 non-null     object
 1   Name         10 non-null     object
 2   Age          10 non-null     int64
 3   Department   10 non-null     object
 4   Salary       10 non-null     int64
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

## df.shape

In [51]:
# Returns a tuple of the rows and columns

df.shape

(10, 5)

## df.describe

In [52]:
# provide statistics of the numerical columns

df.describe()

             Age        Salary
count  10.000000     10.000000
mean   28.800000  54500.000000
std     3.521363  17784.200229
min    24.000000  35000.000000
25%    26.250000  39250.000000
50%    28.500000  49500.000000
75%    30.750000  71000.000000
max    35.000000  81000.000000

## df.columns

In [53]:
# Columns k HEAD / VALUE ko print krta hai

df.columns

Index(['Employee ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

## df.nunique

In [54]:
# unique rows ko print krta hai
                                # number of unique = nunique
df.nunique()

Employee ID    10
Name           10
Age            10
Department      7
Salary         10
dtype: int64