In [2]:
import pandas as pd
df = pd.read_csv("raw_data.csv")

## Feature Engineering
### To transform, create & add some new columns, new features, that improve the performance of our models

## 1) Apply

In [3]:
#        >50k => 20%                   <--- For 'tax' column income slab
#        <= 50k => 10%

df2 = df.copy()

df2['tax'] = df2['income'].apply(lambda x : "20%" if x >= 50000 else "10%")

df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

# Note :  df2['tax'] = df2['income'].apply(lambda x : "20%" if x >= 50000 else "10%")
                                   |------|          |------------------------------|
                                (function main)  ---->    (ek aur function pass krdia/ daala)
                                        |                                  |
                            {High Order Function}  <----  { dusre function ko as a parameter (input) lete hai }

# jb hum kisi function k parameter main koi dusra function pass krte hai jo bahar wala function ko 'High Order Function' hota hai

## 2) Map

In [4]:
# existing values new values k saath map krna chahte hai

In [5]:
gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U"}
df2['gender'] = df2['gender'].map(gender_map)     # to save the values in copy

In [6]:
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

## 3) Assign 
### Can create new columns by assigning them some values

In [7]:
# suppose; increase salary by 1.10  

df2 = df2.assign(new_income = df2['income'] * 1.1)

# new column with new value formed

## 4) Replace
### replace specific old values with new values

In [8]:
# replace USA by US
df2["country"] = df2["country"].replace('USA','US')     # df2 main isliye save kia taaki yeh original ki jo copy hai, usme main save ho jaay
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  20%     63800.0

## 5) Rename
#### Can rename the name of rows and columns

In [17]:
# To change head of all columns

df2.columns = ['Id', 'Name', 'Age', 'Country', 'Gender', 'Income', 'Tax', 'New_Income']  # (Just changing the case for example)


# To change head of particular column
df2.rename(columns = {"Income" : "Salary"})


# To change label of particular row
df2.rename(index= {1 : 'First'})

       Id          Name   Age Country Gender   Income  Tax  New_Income
0       1      John Doe  29.0      US      M  55000.0  20%     60500.0
First   1      John Doe  29.0      US      M  55000.0  20%     60500.0
2       2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3       3          Alex   NaN      US      U  47000.0  10%     51700.0
4       4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5       5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6       6           NaN  45.0   India      F  73000.0  20%     80300.0
7       7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8       8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9       9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10     10   Emily Davis  31.0      US    NaN  58000.0  20%     63800.0

## 6) Sort

### sort_values => Based on Values

In [24]:
# sort_values
df2['Income'].sort_values()    # will view sort of only the income column

# To get this change with whole data
df2.sort_values('Income')

# For ascending / descending order
df2.sort_values('Income', ascending= False)

# To sort using two parameters
sorted_df = df2.sort_values(['Income', 'Age'])      # Fact : If two people with same income, then will be ordered according to age

### sort_index => Based on index

In [26]:
# sort_index
sorted_df.sort_index()

    Id          Name   Age Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  20%     63800.0

## 7) Reset 

### Preserves original index, and will create a new column for new indexes after reset

In [29]:
# Preserves original index, and will create a new column for new indexes after reset
sorted_df.reset_index()

# To drop/delete original index, and to have new column for new indexes after reset
sorted_df.reset_index(drop = True)

    Id          Name   Age Country Gender   Income  Tax  New_Income
0    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
1    3          Alex   NaN      US      U  47000.0  10%     51700.0
2    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
3    1      John Doe  29.0      US      M  55000.0  20%     60500.0
4    1      John Doe  29.0      US      M  55000.0  20%     60500.0
5   10   Emily Davis  31.0      US    NaN  58000.0  20%     63800.0
6    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
7    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
8    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
9    6           NaN  45.0   India      F  73000.0  20%     80300.0
10   4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN

## 8) Rank
### From highest to lowest

In [37]:
sorted_df["Ranking"] = sorted_df['Income'].rank() 
sorted_df        # smallest is getting rank '1'
# clashing/ties/same values will get the average rank of both of them



sorted_df["Ranking"] = sorted_df['Income'].rank(ascending = False) 
sorted_df       # largest is getting rank '1'



sorted_df["Ranking"] = sorted_df['Income'].rank(ascending = False, method = 'dense')  # to avoid average values in ties
sorted_df



sorted_df["Ranking"] = sorted_df['Income'].rank(ascending = False, method = 'min')  # to avoid average values in ties and get minimum value assigned to them
sorted_df



sorted_df["Ranking"] = sorted_df['Income'].rank(ascending = False, method = 'max')  # to avoid average values in ties and get maximum value assigned to them
sorted_df

    Id          Name   Age Country Gender   Income  Tax  New_Income  Ranking
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0     10.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0      9.0
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0      8.0
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0      7.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0      7.0
10  10   Emily Davis  31.0      US    NaN  58000.0  20%     63800.0      5.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      4.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0      4.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0      2.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0      1.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN      NaN

## 9) Reorder
### To reorder columns

In [38]:

# To get 'tax' column at last 
sorted_df[['Id', 'Name', 'Age', 'Country', 'Gender', 'Income', 'New_Income', 'Tax']]

    Id          Name   Age Country Gender   Income  New_Income  Tax
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0     49500.0  10%
3    3          Alex   NaN      US      U  47000.0     51700.0  10%
5    5        Li Wei  27.0   China      M  51000.0     56100.0  20%
0    1      John Doe  29.0      US      M  55000.0     60500.0  20%
1    1      John Doe  29.0      US      M  55000.0     60500.0  20%
10  10   Emily Davis  31.0      US    NaN  58000.0     63800.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0     68200.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0     74800.0  20%
6    6           NaN  45.0   India      F  73000.0     80300.0  20%
4    4  Maria Garcia  34.0   Spain      F      NaN         NaN  10%

In [ ]:
#   Example solved :


# To add the 'id' column in the last in the copy

In [42]:
df2 = df.copy()
new_col_oredr = [col for col in df2.columns if col != 'id'] + ['id']
print(new_col_oredr)

df2[new_col_oredr]

['name', 'age', 'country', 'gender', 'income', 'id']

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10